<?php

namespace CoreBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{

  public function getBilletsFor(\DateTime $date)
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b)')
            ->leftJoin('CoreBundle:Commande', 'c', 'WITH', 'c.id = b.commande_id')
            ->where('c.dateVisite = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
